CREATE PROCEDURE [dbo].[InsertNewAbstracts]
    @AbstractId int output ,
    @PersonId int,
    @ConferenceId int,
    @ConferenceCategoryId int,
    @AbstractTitle nvarchar(500),
    @AbstractIntro ntext,
    @AbstractAuthors nvarchar(4000),
    @CoverLetter ntext,
    @IsAccepted bit,
    @AcceptanceType nvarchar(50),
    @PresentationPath nvarchar(500),
    @PosterPath nvarchar(500),
    @Topic nvarchar(250),
    @Background ntext,
    @Methods ntext,
    @Results ntext,
    @Conclusions ntext,
    @AbstractTerms ntext,
    @AbstractKeywords nvarchar(500),
    @DocumentPath1 nvarchar(250),
    @DocumentPath2 nvarchar(250),
    @DocumentPath3 nvarchar(250),
    @RevisionNumber int,
    @ParentID int,
    @AbstractStatusId int
AS
INSERT INTO [Conference].[Abstracts] (
    [PersonId],
    [ConferenceId],
    [ConferenceCategoryId],
    [AbstractTitle],
    [AbstractIntro],
    [AbstractAuthors],
    [CoverLetter],
    [IsAccepted],
    [AcceptanceType],
    [PresentationPath],
    [PosterPath],
    [Topic],
    [Background],
    [Methods],
    [Results],
    [Conclusions],
    [AbstractTerms],
    [AbstractKeywords],
    [DocumentPath1],
    [DocumentPath2],
    [DocumentPath3],
    [RevisionNumber],
    [ParentID],
    [AbstractStatusId])
Values (
    @PersonId,
    @ConferenceId,
    @ConferenceCategoryId,
    @AbstractTitle,
    @AbstractIntro,
    @AbstractAuthors,
    @CoverLetter,
    @IsAccepted,
    @AcceptanceType,
    @PresentationPath,
    @PosterPath,
    @Topic,
    @Background,
    @Methods,
    @Results,
    @Conclusions,
    @AbstractTerms,
    @AbstractKeywords,
    @DocumentPath1,
    @DocumentPath2,
    @DocumentPath3,
    @RevisionNumber,
    @ParentID,
    @AbstractStatusId)
Set @AbstractId = SCOPE_IDENTITY()

IF @@ROWCOUNT > 0
Select * from Conference.Abstracts
Where [AbstractId] = @@identity


