CREATE PROCEDURE [dbo].[InsertNewEmployees]
    @EmployeeId int,
    @EmployeeNumber nvarchar(50),
    @DepartmentId int,
    @DivisionId int,
    @FormalSiteUrl nvarchar(250),
    @NationalIdNumber nvarchar(50),
    @NationalIdType nchar(1),
    @ManagerId int,
    @BirthDate datetime,
    @MaritalStatus nchar(1),
    @Gender nchar(1),
    @HireDate datetime,
    @SalariedFlag bit,
    @VacationHours smallint,
    @SickLeaveHours smallint,
    @CurrentFlag bit,
    @RowGuid uniqueidentifier,
    @ModifiedDate datetime,
    @Position nvarchar(150)
AS
INSERT INTO [HumanResources].[Employees] (
    [EmployeeId],
    [EmployeeNumber],
    [DepartmentId],
    [DivisionId],
    [FormalSiteUrl],
    [NationalIdNumber],
    [NationalIdType],
    [ManagerId],
    [BirthDate],
    [MaritalStatus],
    [Gender],
    [HireDate],
    [SalariedFlag],
    [VacationHours],
    [SickLeaveHours],
    [CurrentFlag],
    [RowGuid],
    [ModifiedDate],
    [Position])
Values (
    @EmployeeId,
    @EmployeeNumber,
    @DepartmentId,
    @DivisionId,
    @FormalSiteUrl,
    @NationalIdNumber,
    @NationalIdType,
    @ManagerId,
    @BirthDate,
    @MaritalStatus,
    @Gender,
    @HireDate,
    @SalariedFlag,
    @VacationHours,
    @SickLeaveHours,
    @CurrentFlag,
    @RowGuid,
    @ModifiedDate,
    @Position)

IF @@ROWCOUNT > 0
Select * from HumanResources.Employees
Where [EmployeeId] = @EmployeeId
