CREATE PROCEDURE [dbo].[InsertNewPersonExtra]
    @PersonExtraId int,
    @NationalIdType nchar(1),
    @NationalId nvarchar(20),
    @Gender nchar(1),
    @Religion nvarchar(50),
    @BirthDate datetime,
    @BirthPlace nvarchar(50),
    @MaritalStatus nvarchar(50),
    @SpauseName nvarchar(50),
    @FatherGuardianName nvarchar(150),
    @FatherGuardianAddress nvarchar(250),
    @FatherGuardianContactNumber nvarchar(50),
    @EmergencyContactName nvarchar(150),
    @EmergencyContactAddress nvarchar(250),
    @EmergencyContactNumber nvarchar(50),
    @EmergencyContactEmail nvarchar(150),
    @SponsorId int,
    @SponsorStartDate datetime,
    @SponsorEndDate datetime,
    @SponsorCategoryId int,
    @IsGraduateTransfer bit,
    @ReasonForSeekingTransfer nvarchar(250),
    @LevelRequired nvarchar(50),
    @OtherInformation ntext
AS
INSERT INTO [Person].[PersonExtra] (
    [PersonExtraId],
    [NationalIdType],
    [NationalId],
    [Gender],
    [Religion],
    [BirthDate],
    [BirthPlace],
    [MaritalStatus],
    [SpauseName],
    [FatherGuardianName],
    [FatherGuardianAddress],
    [FatherGuardianContactNumber],
    [EmergencyContactName],
    [EmergencyContactAddress],
    [EmergencyContactNumber],
    [EmergencyContactEmail],
    [SponsorId],
    [SponsorStartDate],
    [SponsorEndDate],
    [SponsorCategoryId],
    [IsGraduateTransfer],
    [ReasonForSeekingTransfer],
    [LevelRequired],
    [OtherInformation])
Values (
    @PersonExtraId,
    @NationalIdType,
    @NationalId,
    @Gender,
    @Religion,
    @BirthDate,
    @BirthPlace,
    @MaritalStatus,
    @SpauseName,
    @FatherGuardianName,
    @FatherGuardianAddress,
    @FatherGuardianContactNumber,
    @EmergencyContactName,
    @EmergencyContactAddress,
    @EmergencyContactNumber,
    @EmergencyContactEmail,
    @SponsorId,
    @SponsorStartDate,
    @SponsorEndDate,
    @SponsorCategoryId,
    @IsGraduateTransfer,
    @ReasonForSeekingTransfer,
    @LevelRequired,
    @OtherInformation)

IF @@ROWCOUNT > 0
Select * from Person.PersonExtra
Where [PersonExtraId] = @PersonExtraId
