CREATE PROCEDURE [dbo].[UpdateConferenceRegisterations]
    @OldConferenceRegistererId int,
    @SponsorId int,
    @PersonId int,
    @ConferenceId int,
    @DateRegistered datetime,
    @DiscountAmount decimal(18,2),
    @AmountPaid decimal(18,2),
    @DiscountReason nvarchar(150),
    @RegitrationCategory nvarchar(50),
    @LicenseNumber nvarchar(50),
    @Address nvarchar(50),
    @POBox nvarchar(50),
    @ZipCode nvarchar(50),
    @City nvarchar(50),
    @Country nvarchar(50),
    @PhoneNumberCountryCode nvarchar(50),
    @PhoneNumberAreaCode nvarchar(50),
    @PhoneNumber nvarchar(50),
    @FaxNumberCountryCode nvarchar(50),
    @FaxNumberAreaCode nvarchar(50),
    @FaxNumber nvarchar(50),
    @MobileNumberCountryCode nvarchar(50),
    @MobileNumberAreaCode nvarchar(50),
    @MobileNumber nvarchar(50),
    @Email nvarchar(50),
    @AcademicInformationPosition nvarchar(50),
    @AcademicInformationDegree nvarchar(50),
    @AcademicInformationHealthCarePro bit,
    @AcademicInformationHealthCareProValue nvarchar(50),
    @HospitalInstituteName nvarchar(50),
    @HospitalInstituteDepartment nvarchar(50),
    @HospitalInstituteAddress nvarchar(50),
    @HospitalInstituteZipCode nvarchar(50),
    @HospitalInstituteCity nvarchar(50),
    @HospitalInstituteCountry nvarchar(50),
    @HospitalInstitutePOBox nvarchar(50),
    @ConferenceRegistrationTypeId int,
    @PreConferenceWorkShopIncluded bit,
    @SubscribeToNewsLetter bit,
    @AOAAdministrator bit,
    @AOARetired bit,
    @AOAClinicalResearcher bit,
    @AOABasicResearcher bit,
    @AOATeacherEducator bit,
    @AOAIndustryRepresentative bit,
    @AOAClinicalPractitioner bit,
    @AOAAlliedHealthProfessional bit,
    @AOAStudent bit,
    @AOAOther bit,
    @AOAOtherText nvarchar(500),
    @AOAMCNAcuteKidneyInjury bit,
    @AOAMCNChronicKidneyDisease bit,
    @AOAMCNHypertension bit,
    @AOAMCNGlomerulonephritis bit,
    @AOAMCNNephrolithiasis bit,
    @AOAMRRTHemodialysis bit,
    @AOAMRRTPertionealDialysis bit,
    @AOAMRRTCRRT bit,
    @AOAMPediatricNephrology bit,
    @AOAMGenetics bit,
    @AOAMUrology bit,
    @AOAMMineralMetabolism bit,
    @AOAMAnemia bit,
    @AOAMDiabetes bit,
    @AOAMImmunology bit,
    @AOAMPathology bit,
    @AOAMIterventionalCCN bit,
    @AOAMOther bit,
    @AOAMOtherText nvarchar(500),
    @SponsorName nvarchar(250),
    @DeductedAmount decimal(18,2),
    @IsActive bit ,
    @IsMember bit,
    @IsSelfSponsor bit
AS
UPDATE [Conference].[ConferenceRegisterations]
SET
    SponsorId = @SponsorId,
    PersonId = @PersonId,
    ConferenceId = @ConferenceId,
    DateRegistered = @DateRegistered,
    DiscountAmount = @DiscountAmount,
    AmountPaid = @AmountPaid,
    DiscountReason = @DiscountReason,
    RegitrationCategory = @RegitrationCategory,
    LicenseNumber = @LicenseNumber,
    Address = @Address,
    POBox = @POBox,
    ZipCode = @ZipCode,
    City = @City,
    Country = @Country,
    PhoneNumberCountryCode = @PhoneNumberCountryCode,
    PhoneNumberAreaCode = @PhoneNumberAreaCode,
    PhoneNumber = @PhoneNumber,
    FaxNumberCountryCode = @FaxNumberCountryCode,
    FaxNumberAreaCode = @FaxNumberAreaCode,
    FaxNumber = @FaxNumber,
    MobileNumberCountryCode = @MobileNumberCountryCode,
    MobileNumberAreaCode = @MobileNumberAreaCode,
    MobileNumber = @MobileNumber,
    Email = @Email,
    AcademicInformationPosition = @AcademicInformationPosition,
    AcademicInformationDegree = @AcademicInformationDegree,
    AcademicInformationHealthCarePro = @AcademicInformationHealthCarePro,
    AcademicInformationHealthCareProValue = @AcademicInformationHealthCareProValue,
    HospitalInstituteName = @HospitalInstituteName,
    HospitalInstituteDepartment = @HospitalInstituteDepartment,
    HospitalInstituteAddress = @HospitalInstituteAddress,
    HospitalInstituteZipCode = @HospitalInstituteZipCode,
    HospitalInstituteCity = @HospitalInstituteCity,
    HospitalInstituteCountry = @HospitalInstituteCountry,
    HospitalInstitutePOBox = @HospitalInstitutePOBox,
    ConferenceRegistrationTypeId = @ConferenceRegistrationTypeId,
    PreConferenceWorkShopIncluded = @PreConferenceWorkShopIncluded,
    SubscribeToNewsLetter = @SubscribeToNewsLetter,
    AOAAdministrator = @AOAAdministrator,
    AOARetired = @AOARetired,
    AOAClinicalResearcher = @AOAClinicalResearcher,
    AOABasicResearcher = @AOABasicResearcher,
    AOATeacherEducator = @AOATeacherEducator,
    AOAIndustryRepresentative = @AOAIndustryRepresentative,
    AOAClinicalPractitioner = @AOAClinicalPractitioner,
    AOAAlliedHealthProfessional = @AOAAlliedHealthProfessional,
    AOAStudent = @AOAStudent,
    AOAOther = @AOAOther,
    AOAOtherText = @AOAOtherText,
    AOAMCNAcuteKidneyInjury = @AOAMCNAcuteKidneyInjury,
    AOAMCNChronicKidneyDisease = @AOAMCNChronicKidneyDisease,
    AOAMCNHypertension = @AOAMCNHypertension,
    AOAMCNGlomerulonephritis = @AOAMCNGlomerulonephritis,
    AOAMCNNephrolithiasis = @AOAMCNNephrolithiasis,
    AOAMRRTHemodialysis = @AOAMRRTHemodialysis,
    AOAMRRTPertionealDialysis = @AOAMRRTPertionealDialysis,
    AOAMRRTCRRT = @AOAMRRTCRRT,
    AOAMPediatricNephrology = @AOAMPediatricNephrology,
    AOAMGenetics = @AOAMGenetics,
    AOAMUrology = @AOAMUrology,
    AOAMMineralMetabolism = @AOAMMineralMetabolism,
    AOAMAnemia = @AOAMAnemia,
    AOAMDiabetes = @AOAMDiabetes,
    AOAMImmunology = @AOAMImmunology,
    AOAMPathology = @AOAMPathology,
    AOAMIterventionalCCN = @AOAMIterventionalCCN,
    AOAMOther = @AOAMOther,
    AOAMOtherText = @AOAMOtherText,
    SponsorName = @SponsorName,
    DeductedAmount = @DeductedAmount,
    IsActive = @IsActive,
    IsMember = @IsMember,
    IsSelfSponsor = @IsSelfSponsor
WHERE [ConferenceRegistererId] = @OLDConferenceRegistererId
IF @@ROWCOUNT > 0
Select * From Conference.ConferenceRegisterations 
Where [ConferenceRegistererId] = @OLDConferenceRegistererId
