//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocioBuilderSite.Administrator.Conference.Abstracts {
    
    
    public partial class Abstract {
        
        /// <summary>
        /// AbstractControlMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SocioBuilderSite.Administrator.Conference.Abstracts.Controls.AbstractControl AbstractControlMain;
    }
}
