CREATE TABLE [Conference].[ConferenceRegisterationsLanguage] (
    [ConferenceRegistererId]                INT             IDENTITY (1, 1) NOT NULL,
    [SponsorId]                             INT             NULL,
    [PersonId]                              INT             NULL,
    [ConferenceId]                          INT             NULL,
    [DateRegistered]                        DATETIME        NULL,
    [DiscountAmount]                        DECIMAL (18, 2) NULL,
    [AmountPaid]                            DECIMAL (18, 2) NULL,
    [DiscountReason]                        NVARCHAR (150)  NULL,
    [RegitrationCategory]                   NVARCHAR (50)   NULL,
    [LicenseNumber]                         NVARCHAR (50)   NULL,
    [Address]                               NVARCHAR (50)   NULL,
    [POBox]                                 NVARCHAR (50)   NULL,
    [ZipCode]                               NVARCHAR (50)   NULL,
    [City]                                  NVARCHAR (50)   NULL,
    [Country]                               NVARCHAR (50)   NULL,
    [PhoneNumberCountryCode]                NVARCHAR (50)   NULL,
    [PhoneNumberAreaCode]                   NVARCHAR (50)   NULL,
    [PhoneNumber]                           NVARCHAR (50)   NULL,
    [FaxNumberCountryCode]                  NVARCHAR (50)   NULL,
    [FaxNumberAreaCode]                     NVARCHAR (50)   NULL,
    [FaxNumber]                             NVARCHAR (50)   NULL,
    [MobileNumberCountryCode]               NVARCHAR (50)   NULL,
    [MobileNumberAreaCode]                  NVARCHAR (50)   NULL,
    [MobileNumber]                          NVARCHAR (50)   NULL,
    [Email]                                 NVARCHAR (50)   NULL,
    [AcademicInformationPosition]           NVARCHAR (50)   NULL,
    [AcademicInformationDegree]             NVARCHAR (50)   NULL,
    [AcademicInformationHealthCarePro]      BIT             NULL,
    [AcademicInformationHealthCareProValue] NVARCHAR (50)   NULL,
    [HospitalInstituteName]                 NVARCHAR (50)   NULL,
    [HospitalInstituteDepartment]           NVARCHAR (50)   NULL,
    [HospitalInstituteAddress]              NVARCHAR (50)   NULL,
    [HospitalInstituteZipCode]              NVARCHAR (50)   NULL,
    [HospitalInstituteCity]                 NVARCHAR (50)   NULL,
    [HospitalInstituteCountry]              NVARCHAR (50)   NULL,
    [HospitalInstitutePOBox]                NVARCHAR (50)   NULL,
    [ConferenceRegistrationTypeId]          INT             NULL,
    [PreConferenceWorkShopIncluded]         BIT             NULL,
    [SubscribeToNewsLetter]                 BIT             NULL,
    [AOAAdministrator]                      BIT             NULL,
    [AOARetired]                            BIT             NULL,
    [AOAClinicalResearcher]                 BIT             NULL,
    [AOABasicResearcher]                    BIT             NULL,
    [AOATeacherEducator]                    BIT             NULL,
    [AOAIndustryRepresentative]             BIT             NULL,
    [AOAClinicalPractitioner]               BIT             NULL,
    [AOAAlliedHealthProfessional]           BIT             NULL,
    [AOAStudent]                            BIT             NULL,
    [AOAOther]                              BIT             NULL,
    [AOAOtherText]                          NVARCHAR (500)  NULL,
    [AOAMCNAcuteKidneyInjury]               BIT             NULL,
    [AOAMCNChronicKidneyDisease]            BIT             NULL,
    [AOAMCNHypertension]                    BIT             NULL,
    [AOAMCNGlomerulonephritis]              BIT             NULL,
    [AOAMCNNephrolithiasis]                 BIT             NULL,
    [AOAMRRTHemodialysis]                   BIT             NULL,
    [AOAMRRTPertionealDialysis]             BIT             NULL,
    [AOAMRRTCRRT]                           BIT             NULL,
    [AOAMPediatricNephrology]               BIT             NULL,
    [AOAMGenetics]                          BIT             NULL,
    [AOAMUrology]                           BIT             NULL,
    [AOAMMineralMetabolism]                 BIT             NULL,
    [AOAMAnemia]                            BIT             NULL,
    [AOAMDiabetes]                          BIT             NULL,
    [AOAMImmunology]                        BIT             NULL,
    [AOAMPathology]                         BIT             NULL,
    [AOAMIterventionalCCN]                  BIT             NULL,
    [AOAMOther]                             BIT             NULL,
    [AOAMOtherText]                         NVARCHAR (500)  NULL,
    [SponsorName]                           NVARCHAR (250)  NULL,
    [DeductedAmount]                        DECIMAL (18, 2) NULL,
    [IsActive]                              BIT             NULL,
    [IsMember]                              BIT             NULL,
    [IsSelfSponsor]                         BIT             NULL,
    [ConferenceRegistererParentId]          INT             NOT NULL,
    [LanguageID]                            INT             NOT NULL,
    CONSTRAINT [PK_ConferenceRegisterationsLanguage] PRIMARY KEY CLUSTERED ([ConferenceRegistererId] ASC)
);

