//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConferenceFront {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConferenceFront() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ConferenceFront", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ChangePassword_ConfirmPassword {
            get {
                return ResourceManager.GetString("ChangePassword_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm Password.
        /// </summary>
        internal static string ChangePassword_ConfirmPasswordError {
            get {
                return ResourceManager.GetString("ChangePassword_ConfirmPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Error&lt;/strong&gt;&lt;br /&gt;&lt;span&gt;{0}&lt;/span&gt;.
        /// </summary>
        internal static string ChangePassword_Error {
            get {
                return ResourceManager.GetString("ChangePassword_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword_PageTitle {
            get {
                return ResourceManager.GetString("ChangePassword_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ChangePassword_Password {
            get {
                return ResourceManager.GetString("ChangePassword_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plesae Enter Password.
        /// </summary>
        internal static string ChangePassword_PasswordError {
            get {
                return ResourceManager.GetString("ChangePassword_PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ChangePassword_SaveButton {
            get {
                return ResourceManager.GetString("ChangePassword_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Success&lt;/strong&gt;&lt;br /&gt;&lt;p&gt;Your Password Have Been Updated Successfully&lt;/p&gt;.
        /// </summary>
        internal static string ChangePassword_Success {
            get {
                return ResourceManager.GetString("ChangePassword_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qiyas.
        /// </summary>
        internal static string ConferenceTheme {
            get {
                return ResourceManager.GetString("ConferenceTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already registered.
        /// </summary>
        internal static string ContactForm_RegisteredEmail {
            get {
                return ResourceManager.GetString("ContactForm_RegisteredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string ContactInfo_Address {
            get {
                return ResourceManager.GetString("ContactInfo_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string ContactInfo_City {
            get {
                return ResourceManager.GetString("ContactInfo_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ContactInfo_ConfirmPassword {
            get {
                return ResourceManager.GetString("ContactInfo_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password Must Match.
        /// </summary>
        internal static string ContactInfo_ConfirmPasswordError {
            get {
                return ResourceManager.GetString("ContactInfo_ConfirmPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string ContactInfo_Country {
            get {
                return ResourceManager.GetString("ContactInfo_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string ContactInfo_DateofBirth {
            get {
                return ResourceManager.GetString("ContactInfo_DateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ContactInfo_Email {
            get {
                return ResourceManager.GetString("ContactInfo_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm Password.
        /// </summary>
        internal static string ContactInfo_EnterConfirmPassword {
            get {
                return ResourceManager.GetString("ContactInfo_EnterConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Email.
        /// </summary>
        internal static string ContactInfo_EnterEmail {
            get {
                return ResourceManager.GetString("ContactInfo_EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter First Name.
        /// </summary>
        internal static string ContactInfo_EnterFirstName {
            get {
                return ResourceManager.GetString("ContactInfo_EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Last Name.
        /// </summary>
        internal static string ContactInfo_EnterLastName {
            get {
                return ResourceManager.GetString("ContactInfo_EnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Mobile.
        /// </summary>
        internal static string ContactInfo_EnterMobileNumber {
            get {
                return ResourceManager.GetString("ContactInfo_EnterMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password.
        /// </summary>
        internal static string ContactInfo_EnterPassword {
            get {
                return ResourceManager.GetString("ContactInfo_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Phone.
        /// </summary>
        internal static string ContactInfo_EnterPhone {
            get {
                return ResourceManager.GetString("ContactInfo_EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Title.
        /// </summary>
        internal static string ContactInfo_EnterTitle {
            get {
                return ResourceManager.GetString("ContactInfo_EnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving Data.
        /// </summary>
        internal static string ContactInfo_ErrorMessage {
            get {
                return ResourceManager.GetString("ContactInfo_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Number.
        /// </summary>
        internal static string ContactInfo_FaxNumber {
            get {
                return ResourceManager.GetString("ContactInfo_FaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string ContactInfo_FaxNumberCode {
            get {
                return ResourceManager.GetString("ContactInfo_FaxNumberCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string ContactInfo_FirstName {
            get {
                return ResourceManager.GetString("ContactInfo_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string ContactInfo_Gender {
            get {
                return ResourceManager.GetString("ContactInfo_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string ContactInfo_GenderFemale {
            get {
                return ResourceManager.GetString("ContactInfo_GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string ContactInfo_GenderMale {
            get {
                return ResourceManager.GetString("ContactInfo_GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string ContactInfo_LastName {
            get {
                return ResourceManager.GetString("ContactInfo_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        internal static string ContactInfo_MiddleName {
            get {
                return ResourceManager.GetString("ContactInfo_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        internal static string ContactInfo_MobileNumber {
            get {
                return ResourceManager.GetString("ContactInfo_MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string ContactInfo_MobileNumberCode {
            get {
                return ResourceManager.GetString("ContactInfo_MobileNumberCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ContactInfo_Name {
            get {
                return ResourceManager.GetString("ContactInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ContactInfo_Password {
            get {
                return ResourceManager.GetString("ContactInfo_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters.
        /// </summary>
        internal static string ContactInfo_PasswordError {
            get {
                return ResourceManager.GetString("ContactInfo_PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string ContactInfo_PhoneNumber {
            get {
                return ResourceManager.GetString("ContactInfo_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Contactinfo_PhoneNumberCode {
            get {
                return ResourceManager.GetString("Contactinfo_PhoneNumberCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Box.
        /// </summary>
        internal static string ContactInfo_POBox {
            get {
                return ResourceManager.GetString("ContactInfo_POBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Image.
        /// </summary>
        internal static string ContactInfo_ProfileImage {
            get {
                return ResourceManager.GetString("ContactInfo_ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been successfully signed up to the system. An email has been sent to you for verification. Please Verify your Email to start using site features.
        /// </summary>
        internal static string ContactInfo_ProfileSavedSuccessfully {
            get {
                return ResourceManager.GetString("ContactInfo_ProfileSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated successfully.
        /// </summary>
        internal static string ContactInfo_ProfileUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ContactInfo_ProfileUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ContactInfo_Save {
            get {
                return ResourceManager.GetString("ContactInfo_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ContactInfo_Title {
            get {
                return ResourceManager.GetString("ContactInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr..
        /// </summary>
        internal static string ContactInfo_TitleDr {
            get {
                return ResourceManager.GetString("ContactInfo_TitleDr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss..
        /// </summary>
        internal static string ContactInfo_TitleMiss {
            get {
                return ResourceManager.GetString("ContactInfo_TitleMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr..
        /// </summary>
        internal static string ContactInfo_TitleMr {
            get {
                return ResourceManager.GetString("ContactInfo_TitleMr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs..
        /// </summary>
        internal static string ContactInfo_TitleMrs {
            get {
                return ResourceManager.GetString("ContactInfo_TitleMrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms..
        /// </summary>
        internal static string ContactInfo_TitleMs {
            get {
                return ResourceManager.GetString("ContactInfo_TitleMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prof..
        /// </summary>
        internal static string ContactInfo_TitleProf {
            get {
                return ResourceManager.GetString("ContactInfo_TitleProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string ContactInfo_ZipCode {
            get {
                return ResourceManager.GetString("ContactInfo_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering with us. &lt;br/&gt;&lt;strong style=&quot;font-size:16px;&quot;&gt;Payment Method:&lt;/strong&gt;
        ///&lt;strong&gt;Bank Transfer&lt;/strong&gt;
        ///&lt;p&gt;Workshop payments are paid via bank transfer to the following account:&lt;/p&gt;
        ///&lt;p&gt;Beneficiary: National Center for Assessment in Higher Education&lt;/p&gt;
        ///&lt;p&gt;Account No. (IBAN): &lt;strong&gt;SA8510000025011999000106&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;A copy of bank transfer should be emailed to (ica@qiyas.org) or fax to + 9961 490 7000 ext 7049 &lt;/p&gt;
        ///
        ///&lt;strong&gt;On site / Cash payment&lt;/strong&gt;
        ///&lt;p&gt;Participan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FinishRegistration_Content {
            get {
                return ResourceManager.GetString("FinishRegistration_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SR.
        /// </summary>
        internal static string FinishRegistration_Currency {
            get {
                return ResourceManager.GetString("FinishRegistration_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Completed.
        /// </summary>
        internal static string FinishRegistration_Title {
            get {
                return ResourceManager.GetString("FinishRegistration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string FooterMenu {
            get {
                return ResourceManager.GetString("FooterMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all rights reserved &amp;copy; ica.Qiyas.sa - 2012.
        /// </summary>
        internal static string Footer_CopyRights {
            get {
                return ResourceManager.GetString("Footer_CopyRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ForgetPassword_Email {
            get {
                return ResourceManager.GetString("ForgetPassword_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email you signed up with here. An email will be send with the new generated password..
        /// </summary>
        internal static string ForgetPassword_EmailHelp {
            get {
                return ResourceManager.GetString("ForgetPassword_EmailHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Email.
        /// </summary>
        internal static string ForgetPassword_EmailValidation {
            get {
                return ResourceManager.GetString("ForgetPassword_EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is not registered in the system..
        /// </summary>
        internal static string ForgetPassword_NoticeError {
            get {
                return ResourceManager.GetString("ForgetPassword_NoticeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Password.
        /// </summary>
        internal static string ForgetPassword_SendPassword {
            get {
                return ResourceManager.GetString("ForgetPassword_SendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Email has been send with credentials.
        /// </summary>
        internal static string ForgetPassword_SuccessMessage {
            get {
                return ResourceManager.GetString("ForgetPassword_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        internal static string ForgetPassword_Title {
            get {
                return ResourceManager.GetString("ForgetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Conference/images/banner-1.jpg.
        /// </summary>
        internal static string HomePage_FirstImage {
            get {
                return ResourceManager.GetString("HomePage_FirstImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Conference/Default.aspx?culture=ar.
        /// </summary>
        internal static string HomePage_LanguageLink {
            get {
                return ResourceManager.GetString("HomePage_LanguageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        internal static string HomePage_LanguageText {
            get {
                return ResourceManager.GetString("HomePage_LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string HomePage_Register {
            get {
                return ResourceManager.GetString("HomePage_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Conference/images/banner.jpg.
        /// </summary>
        internal static string HomePage_SecondImage {
            get {
                return ResourceManager.GetString("HomePage_SecondImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Abstract.
        /// </summary>
        internal static string HomePage_Submit {
            get {
                return ResourceManager.GetString("HomePage_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string LoginFront_ChangePassword {
            get {
                return ResourceManager.GetString("LoginFront_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string LoginFront_LoginButton {
            get {
                return ResourceManager.GetString("LoginFront_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string LoginFront_LoginEmail {
            get {
                return ResourceManager.GetString("LoginFront_LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string LoginFront_LoginForgotPassword {
            get {
                return ResourceManager.GetString("LoginFront_LoginForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginFront_LoginH1 {
            get {
                return ResourceManager.GetString("LoginFront_LoginH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginFront_LoginPassword {
            get {
                return ResourceManager.GetString("LoginFront_LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string LoginFront_LoginProfile {
            get {
                return ResourceManager.GetString("LoginFront_LoginProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup for a new account?.
        /// </summary>
        internal static string LoginFront_LoginSignup {
            get {
                return ResourceManager.GetString("LoginFront_LoginSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LoginFront_Logout {
            get {
                return ResourceManager.GetString("LoginFront_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Conference/images/ar.jpg.
        /// </summary>
        internal static string MasterPage_LanguageImage {
            get {
                return ResourceManager.GetString("MasterPage_LanguageImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string MediaReference_Date {
            get {
                return ResourceManager.GetString("MediaReference_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string MediaReference_Logo {
            get {
                return ResourceManager.GetString("MediaReference_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string MediaReference_Reference {
            get {
                return ResourceManager.GetString("MediaReference_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string MediaReference_Title {
            get {
                return ResourceManager.GetString("MediaReference_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer.
        /// </summary>
        internal static string OrganizerSectionHeader {
            get {
                return ResourceManager.GetString("OrganizerSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Conference/images/tab-left.png.
        /// </summary>
        internal static string PageTab_LeftImage {
            get {
                return ResourceManager.GetString("PageTab_LeftImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Conference/images/tab-right.png.
        /// </summary>
        internal static string PageTab_RightImage {
            get {
                return ResourceManager.GetString("PageTab_RightImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Conference/images/left-selected.png.
        /// </summary>
        internal static string PageTab_SelectedLeftImage {
            get {
                return ResourceManager.GetString("PageTab_SelectedLeftImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Conference/images/right-selected.png.
        /// </summary>
        internal static string PageTab_SelectedRightImage {
            get {
                return ResourceManager.GetString("PageTab_SelectedRightImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAR.
        /// </summary>
        internal static string PaymentCurrency {
            get {
                return ResourceManager.GetString("PaymentCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string ProfileInformation_Address {
            get {
                return ResourceManager.GetString("ProfileInformation_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string ProfileInformation_City {
            get {
                return ResourceManager.GetString("ProfileInformation_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string ProfileInformation_Country {
            get {
                return ResourceManager.GetString("ProfileInformation_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string ProfileInformation_DateofBirth {
            get {
                return ResourceManager.GetString("ProfileInformation_DateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string ProfileInformation_EditProfile {
            get {
                return ResourceManager.GetString("ProfileInformation_EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Number.
        /// </summary>
        internal static string ProfileInformation_FaxNumber {
            get {
                return ResourceManager.GetString("ProfileInformation_FaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string ProfileInformation_Gender {
            get {
                return ResourceManager.GetString("ProfileInformation_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        internal static string ProfileInformation_MobileNumber {
            get {
                return ResourceManager.GetString("ProfileInformation_MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string ProfileInformation_PhoneNumber {
            get {
                return ResourceManager.GetString("ProfileInformation_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Box.
        /// </summary>
        internal static string ProfileInformation_POBox {
            get {
                return ResourceManager.GetString("ProfileInformation_POBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string ProfileInformation_ZipCode {
            get {
                return ResourceManager.GetString("ProfileInformation_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string RegisterationForm_Finish {
            get {
                return ResourceManager.GetString("RegisterationForm_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Registeration_ConfirmAddress {
            get {
                return ResourceManager.GetString("Registeration_ConfirmAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Registeration_ConfirmBusinessPhone {
            get {
                return ResourceManager.GetString("Registeration_ConfirmBusinessPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        internal static string Registeration_ConfirmDate {
            get {
                return ResourceManager.GetString("Registeration_ConfirmDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Registeration_ConfirmEmail {
            get {
                return ResourceManager.GetString("Registeration_ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Registeration_ConfirmFullName {
            get {
                return ResourceManager.GetString("Registeration_ConfirmFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the information you have entered and click Finish.
        /// </summary>
        internal static string Registeration_ConfirmTitle {
            get {
                return ResourceManager.GetString("Registeration_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string RegisterPage_Signup {
            get {
                return ResourceManager.GetString("RegisterPage_Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Information.
        /// </summary>
        internal static string RegistrationForm_AcademicInformation {
            get {
                return ResourceManager.GetString("RegistrationForm_AcademicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Item Response Theory in Test Development.
        /// </summary>
        internal static string RegistrationForm_AlliedHealthProfessional {
            get {
                return ResourceManager.GetString("RegistrationForm_AlliedHealthProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bs..
        /// </summary>
        internal static string RegistrationForm_Bachelor {
            get {
                return ResourceManager.GetString("RegistrationForm_Bachelor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string RegistrationForm_Back {
            get {
                return ResourceManager.GetString("RegistrationForm_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string RegistrationForm_Confirmation {
            get {
                return ResourceManager.GetString("RegistrationForm_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check here to confirm your information.
        /// </summary>
        internal static string RegistrationForm_ConfirmMessage {
            get {
                return ResourceManager.GetString("RegistrationForm_ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        internal static string RegistrationForm_Degree {
            get {
                return ResourceManager.GetString("RegistrationForm_Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string RegistrationForm_DegreeOther {
            get {
                return ResourceManager.GetString("RegistrationForm_DegreeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dietitian.
        /// </summary>
        internal static string RegistrationForm_Dietitian {
            get {
                return ResourceManager.GetString("RegistrationForm_Dietitian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string RegistrationForm_Finish {
            get {
                return ResourceManager.GetString("RegistrationForm_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Care Professional.
        /// </summary>
        internal static string RegistrationForm_HealthCareProfessional {
            get {
                return ResourceManager.GetString("RegistrationForm_HealthCareProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string RegistrationForm_HospitalAddress {
            get {
                return ResourceManager.GetString("RegistrationForm_HospitalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string RegistrationForm_HospitalDepartment {
            get {
                return ResourceManager.GetString("RegistrationForm_HospitalDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Organization.
        /// </summary>
        internal static string RegistrationForm_HospitalInstitude {
            get {
                return ResourceManager.GetString("RegistrationForm_HospitalInstitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string RegistrationForm_HospitalName {
            get {
                return ResourceManager.GetString("RegistrationForm_HospitalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///    &lt;li&gt;
        ///    Conference lectures attendance is FREE.
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///    Conference Sessions and Workshops Registration Deadline from outside the Kingdom is 6th October 2012.
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///    All Workshops will be held in King Faisal Conference Auditorium in Riyadh InterContinental as per Dates, Time and Halls shown in below table.
        ///Workshop seats are limited.
        ///
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///    Workshop Registration Fees :
        ///    &lt;ul&gt;
        ///        &lt;li&gt;
        ///        Early Registration up to 2nd November [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegistrationForm_Information {
            get {
                return ResourceManager.GetString("RegistrationForm_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Number.
        /// </summary>
        internal static string RegistrationForm_LicenseNumber {
            get {
                return ResourceManager.GetString("RegistrationForm_LicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are practicing in Saudi Arabia please enter Saudi Commission For Health Specialties Licensing Number(to claim your CME hours).
        /// </summary>
        internal static string RegistrationForm_LicenseNumberDescription {
            get {
                return ResourceManager.GetString("RegistrationForm_LicenseNumberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD..
        /// </summary>
        internal static string RegistrationForm_Masters {
            get {
                return ResourceManager.GetString("RegistrationForm_Masters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBBS..
        /// </summary>
        internal static string RegistrationForm_MBBS {
            get {
                return ResourceManager.GetString("RegistrationForm_MBBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Doctor.
        /// </summary>
        internal static string RegistrationForm_MedicalDoctor {
            get {
                return ResourceManager.GetString("RegistrationForm_MedicalDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string RegistrationForm_Member {
            get {
                return ResourceManager.GetString("RegistrationForm_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        internal static string RegistrationForm_Membership {
            get {
                return ResourceManager.GetString("RegistrationForm_Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string RegistrationForm_Next {
            get {
                return ResourceManager.GetString("RegistrationForm_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Member.
        /// </summary>
        internal static string RegistrationForm_NonMember {
            get {
                return ResourceManager.GetString("RegistrationForm_NonMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurse.
        /// </summary>
        internal static string RegistrationForm_Nurse {
            get {
                return ResourceManager.GetString("RegistrationForm_Nurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ph.D..
        /// </summary>
        internal static string RegistrationForm_PhD {
            get {
                return ResourceManager.GetString("RegistrationForm_PhD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physiotherapist.
        /// </summary>
        internal static string RegistrationForm_Physiotherapist {
            get {
                return ResourceManager.GetString("RegistrationForm_Physiotherapist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string RegistrationForm_Position {
            get {
                return ResourceManager.GetString("RegistrationForm_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monte Carlo Simulation Using R.
        /// </summary>
        internal static string RegistrationForm_PreConferenceWorkshop {
            get {
                return ResourceManager.GetString("RegistrationForm_PreConferenceWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Development.
        /// </summary>
        internal static string RegistrationForm_PreConferenceWorkshop2 {
            get {
                return ResourceManager.GetString("RegistrationForm_PreConferenceWorkshop2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Information.
        /// </summary>
        internal static string RegistrationForm_RegistrarInformation {
            get {
                return ResourceManager.GetString("RegistrationForm_RegistrarInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Category.
        /// </summary>
        internal static string RegistrationForm_RegistrationCategory {
            get {
                return ResourceManager.GetString("RegistrationForm_RegistrationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Confirmation.
        /// </summary>
        internal static string RegistrationForm_RegistrationConfirmation {
            get {
                return ResourceManager.GetString("RegistrationForm_RegistrationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string RegistrationForm_RegistrationFee {
            get {
                return ResourceManager.GetString("RegistrationForm_RegistrationFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respiratory Therapist.
        /// </summary>
        internal static string RegistrationForm_RespiratoryTherapist {
            get {
                return ResourceManager.GetString("RegistrationForm_RespiratoryTherapist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Sponsor.
        /// </summary>
        internal static string RegistrationForm_SelfSponsor {
            get {
                return ResourceManager.GetString("RegistrationForm_SelfSponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string RegistrationForm_SponsorOther {
            get {
                return ResourceManager.GetString("RegistrationForm_SponsorOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsorship Type.
        /// </summary>
        internal static string RegistrationForm_SponsorshipType {
            get {
                return ResourceManager.GetString("RegistrationForm_SponsorshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string RegistrationForm_Submit {
            get {
                return ResourceManager.GetString("RegistrationForm_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string RegistrationForm_Tab3 {
            get {
                return ResourceManager.GetString("RegistrationForm_Tab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;br /&gt;.
        /// </summary>
        internal static string RegistrationForm_TableAfterReg1 {
            get {
                return ResourceManager.GetString("RegistrationForm_TableAfterReg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string RegistrationForm_TableAfterReg2 {
            get {
                return ResourceManager.GetString("RegistrationForm_TableAfterReg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width:100%;&quot;&gt;
        ///&lt;tr&gt;
        ///    &lt;td colspan=&quot;2&quot; style=&quot;font-weight:bold;text-align:center;&quot;&gt;Sat.  December 1st  , 2012&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr style=&quot;background-color:#18335F;color:#FFFFFF;&quot;&gt;
        ///    &lt;td style=&quot;text-align:center;&quot;&gt;
        ///    Time
        ///    &lt;/td&gt;
        ///&lt;td style=&quot;text-align:center;&quot;&gt;
        ///    1st  Workshop :  This workshop will be held in English
        ///    &lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///    &lt;td&gt;
        ///    8:00 – 16:30
        ///    &lt;/td&gt;
        ///    &lt;td style=&quot;font-weight:bold;&quot;&gt;.
        /// </summary>
        internal static string RegistrationForm_TableBeforeReg1 {
            get {
                return ResourceManager.GetString("RegistrationForm_TableBeforeReg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width:100%;&quot;&gt;
        ///&lt;tr&gt;
        ///    &lt;td colspan=&quot;2&quot; style=&quot;font-weight:bold;text-align:center;&quot;&gt; Sun.  December 2nd , 2012&lt;/td&gt;
        ///    &lt;/tr&gt;
        /// &lt;tr style=&quot;background-color:#18335F;color:#FFFFFF;&quot;&gt;
        ///    &lt;td style=&quot;text-align:center;&quot;&gt;
        ///            Time
        ///        &lt;/td&gt;
        ///         &lt;td style=&quot;text-align:center;&quot;&gt;
        ///        2nd  Workshop :  This workshop will be held in English
        ///        &lt;/td&gt;
        ///        &lt;td style=&quot;text-align:center;&quot;&gt;
        ///        3rd  Workshop :  This workshop will be held in Arabic 
        ///        &lt;/td&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegistrationForm_TableBeforeReg2 {
            get {
                return ResourceManager.GetString("RegistrationForm_TableBeforeReg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/td&gt;
        ///        &lt;td style=&quot;font-weight:bold;&quot;&gt;.
        /// </summary>
        internal static string RegistrationForm_TableBetReg2 {
            get {
                return ResourceManager.GetString("RegistrationForm_TableBetReg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string RegistrationForm_Time {
            get {
                return ResourceManager.GetString("RegistrationForm_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Form.
        /// </summary>
        internal static string RegistrationForm_Title {
            get {
                return ResourceManager.GetString("RegistrationForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SR.
        /// </summary>
        internal static string Registration_Currency {
            get {
                return ResourceManager.GetString("Registration_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Registration_Total {
            get {
                return ResourceManager.GetString("Registration_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to register online or submit an abstract for &lt;strong&gt;The Conference&lt;/strong&gt;, you must be &lt;strong&gt;logged in&lt;/strong&gt;.&lt;/span&gt;&lt;br /&gt;&lt;br /&gt;Please &lt;strong&gt;login&lt;/strong&gt; with your email address and password using the form on the left.&lt;br /&gt;If you cannot remember your password you can retrieve it using the &lt;strong&gt;&lt;a runat=&quot;server&quot; id=&quot;A1&quot; href=&quot;ForgetPassword.aspx&quot;&gt;forgot password&lt;/a&gt;&lt;/strong&gt; form.&lt;br /&gt;If you don&apos;t have an account yet kindly use the &lt;strong&gt;&lt;a runat=&quot;server&quot; id=&quot;SignupFormLink&quot; href= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestLogin_Content {
            get {
                return ResourceManager.GetString("RequestLogin_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Login.
        /// </summary>
        internal static string RequestLogin_Title {
            get {
                return ResourceManager.GetString("RequestLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string SchedulerSectionHeader {
            get {
                return ResourceManager.GetString("SchedulerSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string SiteMenu {
            get {
                return ResourceManager.GetString("SiteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker Information.
        /// </summary>
        internal static string SpeakersInfo_Title {
            get {
                return ResourceManager.GetString("SpeakersInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers.
        /// </summary>
        internal static string SpeakersSectionHeader {
            get {
                return ResourceManager.GetString("SpeakersSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers.
        /// </summary>
        internal static string SpeakersTitle {
            get {
                return ResourceManager.GetString("SpeakersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More About.
        /// </summary>
        internal static string Speakers_MoreAbout {
            get {
                return ResourceManager.GetString("Speakers_MoreAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Conference/images/c_en.jpg.
        /// </summary>
        internal static string SponsorControl_ImagePath {
            get {
                return ResourceManager.GetString("SponsorControl_ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/ContentData/SponsershipBrochureEnglishLast.pdf.
        /// </summary>
        internal static string SponsorControl_ImagePathLink {
            get {
                return ResourceManager.GetString("SponsorControl_ImagePathLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsors.
        /// </summary>
        internal static string SponsorsSectionHeader {
            get {
                return ResourceManager.GetString("SponsorsSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Date.
        /// </summary>
        internal static string TimeandDate {
            get {
                return ResourceManager.GetString("TimeandDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string TopMenu {
            get {
                return ResourceManager.GetString("TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel &amp; Transportation.
        /// </summary>
        internal static string TravelView_Title {
            get {
                return ResourceManager.GetString("TravelView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Tweets.
        /// </summary>
        internal static string TwitterBox_Title {
            get {
                return ResourceManager.GetString("TwitterBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure City.
        /// </summary>
        internal static string VisaRequest_City {
            get {
                return ResourceManager.GetString("VisaRequest_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string VisaRequest_Company {
            get {
                return ResourceManager.GetString("VisaRequest_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Country.
        /// </summary>
        internal static string VisaRequest_Country {
            get {
                return ResourceManager.GetString("VisaRequest_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Approved.
        /// </summary>
        internal static string VisaRequest_IsOrganizationApproved {
            get {
                return ResourceManager.GetString("VisaRequest_IsOrganizationApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Taken.
        /// </summary>
        internal static string VisaRequest_IsTaken {
            get {
                return ResourceManager.GetString("VisaRequest_IsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Position.
        /// </summary>
        internal static string VisaRequest_Job {
            get {
                return ResourceManager.GetString("VisaRequest_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        internal static string VisaRequest_PassportAttachment {
            get {
                return ResourceManager.GetString("VisaRequest_PassportAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        internal static string VisaRequest_Religion {
            get {
                return ResourceManager.GetString("VisaRequest_Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering, will look into the submitted information and then send the visa request.
        /// </summary>
        internal static string VisaRequest_SuccessMessage {
            get {
                return ResourceManager.GetString("VisaRequest_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The Conference General Directorate will not guarantee the issuing of entry visa for Workshop/s Registered Attendants after registration deadline of 6 October 2012.
        /// </summary>
        internal static string VisaRequest_Summary {
            get {
                return ResourceManager.GetString("VisaRequest_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Request.
        /// </summary>
        internal static string VisaRequest_Title {
            get {
                return ResourceManager.GetString("VisaRequest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Attachment.
        /// </summary>
        internal static string VisaRequest_VisaAttachment {
            get {
                return ResourceManager.GetString("VisaRequest_VisaAttachment", resourceCulture);
            }
        }
    }
}
